---
#
#  __  __           _              ____           _
# |  \/  | __ _ ___| |_ ___ _ __  | __ )  ___  __| |_ __ ___   ___  _ __ ___
# | |\/| |/ _` / __| __/ _ \ '__| |  _ \ / _ \/ _` | '__/ _ \ / _ \| '_ ` _ \
# | |  | | (_| \__ \ ||  __/ |    | |_) |  __/ (_| | | | (_) | (_) | | | | | |
# |_|  |_|\__,_|___/\__\___|_|    |____/ \___|\__,_|_|  \___/ \___/|_| |_| |_|
#

#############################################
###   do you want to keep the lights on?   ##
#############################################

- alias: "Actionable notification: Mark master bedroom as busy"
  mode: single
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_mark_bedrom_busy
        event_response_type: ResponseYes
  condition: []
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.busy_in_master_bedroom
    - delay: 00:15:00
    - service: script.activate_alexa_actionable_notification
      data:
        text: are you still here?
        event_id: actionable_notification_master_bedroom_still_busy
        alexa_device: media_player.jesus_s_echo_dot_bedroom

##########################################
###         are you still here?         ##
##########################################
# Yes
- alias: "Actionable notification: Keep asking if still busy in master bedroom"
  mode: single
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_master_bedroom_still_busy
        event_response_type: ResponseYes
  condition: []
  action:
    - delay: 00:15:00
    - service: script.activate_alexa_actionable_notification
      data:
        text: are you still here?
        event_id: actionable_notification_master_bedroom_still_busy
        alexa_device: media_player.jesus_s_echo_dot_bedroom

# No
- alias: "Actionable notification: masterbedroom not busy with response no"
  mode: single
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_master_bedroom_still_busy
        event_response_type: ResponseNo
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_master_bedroom_still_busy
        event_response_type: ResponseNone
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_master_bedroom_still_busy
        event_response_type: ResponseString
  condition: []
  action:
    - type: turn_off
      device_id: 70aafa9b1a197b098fb51da48359d776
      entity_id: light.loft_ceiling_fan_light
      domain: light
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.busy_in_master_bedroom

#  _    _ _       _
# | | _(_) |_ ___| |__   ___ _ __
# | |/ / | __/ __| '_ \ / _ \ '_ \
# |   <| | || (__| | | |  __/ | | |
# |_|\_\_|\__\___|_| |_|\___|_| |_|
#

##########################################
###         are you still here?         ##
##########################################

# Yes
- alias: "Actionable notification: Keep asking if still here in kitchen"
  mode: single
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_kitchen_still_busy
        event_response_type: ResponseYes
  condition: []
  action:
    - delay: 00:15:00
    - service: script.activate_alexa_actionable_notification
      data:
        text: are you still here?
        event_id: actionable_notification_kitchen_still_busy
        alexa_device: media_player.jesus_s_7th_echo_dot

# No
- alias: "Actionable notification: kitchen not busy with response no"
  mode: single
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_kitchen_still_busy
        event_response_type: ResponseNo
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_kitchen_still_busy
        event_response_type: ResponseNone
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_kitchen_still_busy
        event_response_type: ResponseString
  condition: []
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.busy_in_kitchen
    - if:
        - condition: state
          entity_id: binary_sensor.lumi_lumi_motion_ac02_ias_zone
          state: "off"
      then:
        - type: turn_off
          device_id: b6ecb1786d89951862e4f0a8301302bd
          entity_id: light.kitchen_main_lights
          domain: light
