---
#-
#                  _             _                  _ _       _
#   ___ ___  _ __ | |_ _ __ ___ | |    _____      _(_) |_ ___| |__   ___  ___
#  / __/ _ \| '_ \| __| '__/ _ \| |   / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# | (_| (_) | | | | |_| | | (_) | |   \__ \\ V  V /| | || (__| | | |  __/\__ \
#  \___\___/|_| |_|\__|_|  \___/|_|___|___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#                                |_____|
#

#  _  ___ _       _
# | |/ (_) |_ ___| |__   ___ _ __
# | ' /| | __/ __| '_ \ / _ \ '_ \
# | . \| | || (__| | | |  __/ | | |
# |_|\_\_|\__\___|_| |_|\___|_| |_|
#
- alias: "Control switches: mark kitchen busy"
  description: when clicking the button busy in kitchen is on
  trigger:
    - device_id: 1138a5f9bce2aaed6b7b75cba6cdabf6
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
    - device_id: aee89585cb6a8d9bf73b98bef7f0387c
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.busy_in_kitchen
    - type: turn_on
      device_id: b6ecb1786d89951862e4f0a8301302bd
      entity_id: switch.kitchen_main_lights
      domain: switch
    - delay: 00:15:00
    - service: script.activate_alexa_actionable_notification
      data:
        text: Should I keep lights on?
        event_id: actionable_notification_kitchen_still_busy
        alexa_device: media_player.jesus_s_7th_echo_dot
  mode: single

- alias: "Control switches: mark kitchen as not bussy"
  description: make busy in kitchen status to be null
  trigger:
    - device_id: 1138a5f9bce2aaed6b7b75cba6cdabf6
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
    - device_id: aee89585cb6a8d9bf73b98bef7f0387c
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    - type: turn_off
      device_id: b6ecb1786d89951862e4f0a8301302bd
      entity_id: switch.kitchen_main_lights
      domain: switch
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.busy_in_kitchen
  mode: single

#    __  __           _              _              _
# |  \/  | __ _ ___| |_ ___ _ __  | |__   ___  __| |_ __ ___   ___  _ __ ___
# | |\/| |/ _` / __| __/ _ \ '__| | '_ \ / _ \/ _` | '__/ _ \ / _ \| '_ ` _ \
# | |  | | (_| \__ \ ||  __/ |    | |_) |  __/ (_| | | | (_) | (_) | | | | | |
# |_|  |_|\__,_|___/\__\___|_|    |_.__/ \___|\__,_|_|  \___/ \___/|_| |_| |_|
#
- alias: "Control switches: ready to sleep"
  description:
    prepares room to sleep and read Alexa notification of door devices
    status
  trigger:
    - device_id: c793e4ce34753abd80b6a18c6df7bd2c
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    service: script.going_to_sleep
  mode: single

- alias: "Control switches: Master Bedroom Actionable lights"
  description: alexa will ask if room is busy
  trigger:
    - device_id: c793e4ce34753abd80b6a18c6df7bd2c
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - type: turn_on
      device_id: ec0c8c237f75405507b5c3329aebe55c
      entity_id: light.bedroom_fan_light
      domain: light
    - service: script.activate_alexa_actionable_notification
      data:
        text: Should I keep lights on?
        event_id: actionable_notification_mark_bedrom_busy
        alexa_device: media_player.jesus_s_echo_dot_bedroom
  mode: single

#  _     _       _               ____
# | |   (_)_   _(_)_ __   __ _  |  _ \ ___   ___  _ __ ___
# | |   | \ \ / / | '_ \ / _` | | |_) / _ \ / _ \| '_ ` _ \
# | |___| |\ V /| | | | | (_| | |  _ < (_) | (_) | | | | | |
# |_____|_| \_/ |_|_| |_|\__, | |_| \_\___/ \___/|_| |_| |_|
#                        |___/

- alias: "Control switches: open blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - parallel:
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.living_room_blinds
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.dining_blinds
  mode: single

- alias: "Control switches: close blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    - parallel:
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.living_room_blinds
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.dining_blinds
  mode: single

- alias: "Control switches: half open blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_long_release
      subtype: open
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_long_release
      subtype: close
  condition: []
  action:
    - parallel:
        - service: cover.set_cover_position
          entity_id: cover.living_room_blinds
          data:
            position: 50
        - service: cover.set_cover_position
          entity_id: cover.dining_blinds
          data:
            position: 50
  mode: single
