---
#-
#                  _             _                  _ _       _
#   ___ ___  _ __ | |_ _ __ ___ | |    _____      _(_) |_ ___| |__   ___  ___
#  / __/ _ \| '_ \| __| '__/ _ \| |   / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# | (_| (_) | | | | |_| | | (_) | |   \__ \\ V  V /| | || (__| | | |  __/\__ \
#  \___\___/|_| |_|\__|_|  \___/|_|___|___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#                                |_____|
#

#  _  ___ _       _
# | |/ (_) |_ ___| |__   ___ _ __
# | ' /| | __/ __| '_ \ / _ \ '_ \
# | . \| | || (__| | | |  __/ | | |
# |_|\_\_|\__\___|_| |_|\___|_| |_|
#
- alias: "Control switches: mark kitchen busy"
  description: when clicking the button busy in kitchen is on
  trigger:
    - device_id: 8d6694c6e4b06b7a9fed47676ece2469
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.busy_in_kitchen
    - type: turn_on
      device_id: 1899af3967b4c4b386e8cc9b8576179f
      entity_id: light.kitchen_main_lights_light_2
      domain: light
      brightness_pct: 100
    - delay: 00:15:00
    - service: script.activate_alexa_actionable_notification
      data:
        text: Are you still here?
        event_id: actionable_notification_kitchen_still_busy
        alexa_device: media_player.jesus_s_7th_echo_dot
  mode: single

- alias: "Control switches: mark kitchen as not bussy"
  description: make busy in kitchen status to be null
  trigger:
    - device_id: 8d6694c6e4b06b7a9fed47676ece2469
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    - type: turn_off
      device_id: 1899af3967b4c4b386e8cc9b8576179f
      entity_id: light.kitchen_main_lights_light_2
      domain: light
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.busy_in_kitchen
  mode: single

- alias: "Control switches: turn on bar lights with remote"
  description: when clicking the button on in bar
  trigger:
    - device_id: 7e20e872ef049b84ffcf66505ddb5946
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - type: turn_on
      device_id: b6ecb1786d89951862e4f0a8301302bd
      entity_id: light.kitchen_island_pendants
      domain: light

- alias: "Control switches: turn off bar lights with remote"
  description: when clicking the button on in bar
  trigger:
    - device_id: 7e20e872ef049b84ffcf66505ddb5946
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    - type: turn_off
      device_id: b6ecb1786d89951862e4f0a8301302bd
      entity_id: light.kitchen_island_pendants
      domain: light

#    __  __           _              _              _
# |  \/  | __ _ ___| |_ ___ _ __  | |__   ___  __| |_ __ ___   ___  _ __ ___
# | |\/| |/ _` / __| __/ _ \ '__| | '_ \ / _ \/ _` | '__/ _ \ / _ \| '_ ` _ \
# | |  | | (_| \__ \ ||  __/ |    | |_) |  __/ (_| | | | (_) | (_) | | | | | |
# |_|  |_|\__,_|___/\__\___|_|    |_.__/ \___|\__,_|_|  \___/ \___/|_| |_| |_|
#
- alias: "Control switches: ready to sleep"
  description:
    prepares room to sleep and read Alexa notification of door devices
    status
  trigger:
    - device_id: 5a68702aff4c766e1b13df267abdc4c9
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    service: script.going_to_sleep
  mode: single

- alias: "Control switches: Master Bedroom Actionable lights"
  description: alexa will ask if room is busy
  trigger:
    - device_id: 5a68702aff4c766e1b13df267abdc4c9
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - type: turn_on
      device_id: c6fb0ddc8a44f44185180b7614664533
      entity_id: light.inovelli_vzm31_sn_light_4
      domain: light
      brightness_pct: 100
    - service: script.activate_alexa_actionable_notification
      data:
        text: Should I keep lights on?
        event_id: actionable_notification_mark_bedrom_busy
        alexa_device: media_player.jesus_s_echo_dot_bedroom
  mode: single

#  _     _       _               ____
# | |   (_)_   _(_)_ __   __ _  |  _ \ ___   ___  _ __ ___
# | |   | \ \ / / | '_ \ / _` | | |_) / _ \ / _ \| '_ ` _ \
# | |___| |\ V /| | | | | (_| | |  _ < (_) | (_) | | | | | |
# |_____|_| \_/ |_|_| |_|\__, | |_| \_\___/ \___/|_| |_| |_|
#                        |___/

- alias: "Control switches: open blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: open
  condition: []
  action:
    - parallel:
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.living_room_blinds
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.dining_blinds
  mode: single

- alias: "Control switches: close blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: close
  condition: []
  action:
    - parallel:
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.living_room_blinds
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.dining_blinds
  mode: single

- alias: "Control switches: half open blinds"
  description: ""
  trigger:
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_long_release
      subtype: open
    - device_id: 4867819545acb4446df7f0ee8dc34188
      domain: zha
      platform: device
      type: remote_button_long_release
      subtype: close
  condition: []
  action:
    - parallel:
        - service: cover.set_cover_position
          entity_id: cover.living_room_blinds
          data:
            position: 50
        - service: cover.set_cover_position
          entity_id: cover.dining_blinds
          data:
            position: 50
  mode: single
