#-
#                     _ _                  _
#  _ __ ___   ___  __| (_) __ _      _ __ | | __ _ _   _  ___ _ __
# | '_ ` _ \ / _ \/ _` | |/ _` |    | '_ \| |/ _` | | | |/ _ \ '__|
# | | | | | |  __/ (_| | | (_| |    | |_) | | (_| | |_| |  __/ |
# |_| |_| |_|\___|\__,_|_|\__,_|____| .__/|_|\__,_|\__, |\___|_|
#                             |_____|_|            |___/
#

#  _     _       _                                         
# | |   (_)_   _(_)_ __   __ _   _ __ ___   ___  _ __ ___  
# | |   | \ \ / / | '_ \ / _` | | '__/ _ \ / _ \| '_ ` _ \ 
# | |___| |\ V /| | | | | (_| | | | | (_) | (_) | | | | | |
# |_____|_| \_/ |_|_| |_|\__, | |_|  \___/ \___/|_| |_| |_|
#                        |___/                             

- alias: "Media player: Watching Apple TV on living room"
  description: Turns on onkyo receiver when apple tv wakes and turn off lights
  trigger:
  - platform: device
    device_id: 28adeb2341843c3807d1e8cb3029ea1d
    domain: media_player
    entity_id: media_player.living_room
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id:
      - media_player.receiver
      - media_player.receiver_zone_2
  - type: turn_off
    device_id: e97cd70c4660d3f773bccb57a70ccac8
    entity_id: switch.living_room_main_lights
    domain: switch
  - type: turn_off
    device_id: b04b8561152faed1f9f75fe8fc4d0ff3
    entity_id: switch.living_room_ceiling_fan_light
    domain: switch
  - if:
    - condition: sun
      before: sunset
    then:
    - service: script.1663028119276
      data: {}
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.watching_in_living_room
  - if:
    - condition: state
      entity_id: input_boolean.busy_in_kitchen
      state: 'off'
    then:
    - type: turn_off
      device_id: b6ecb1786d89951862e4f0a8301302bd
      entity_id: switch.kitchen_main_lights
      domain: switch
  mode: single

- alias: "Media player: turn off watching in living room status when Apple TV is idle"
  description: ''
  trigger:
  - platform: device
    device_id: 28adeb2341843c3807d1e8cb3029ea1d
    domain: media_player
    entity_id: media_player.living_room
    type: idle
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.watching_in_living_room
  mode: single  


#  _           __ _   
# | |    ___  / _| |_ 
# | |   / _ \| |_| __|
# | |__| (_) |  _| |_ 
# |_____\___/|_|  \__|
#                     
- alias: "Media player: Watching tv on loft"
  description: ''
  trigger:
  - platform: device
    device_id: 5bd9b4a8b1c3edcbf04af45422c6b171
    domain: media_player
    entity_id: media_player.loft
    type: playing
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.watching_in_loft  
  - if:
    - condition: state
      entity_id: input_boolean.busy_in_loft
      state: 'off'
    then:
      - type: turn_off
        device_id: 70aafa9b1a197b098fb51da48359d776
        entity_id: light.loft_ceiling_fan_light
        domain: light
      - type: turn_off
        device_id: 94bf24a5171d66dd1057e8fc9a13d6fa
        entity_id: light.inovelli_vzm31_sn_light
        domain: ligh
  mode: single

- alias: "Media player: turn off watching in loft status when Apple TV is idle"
  description: ''
  trigger:
  - platform: device
    device_id: 28adeb2341843c3807d1e8cb3029ea1d
    domain: media_player
    entity_id: media_player.living_room
    type: idle
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.watching_in_loft
  mode: single    