---
#        _   _ _ _ _   _
#  _   _| |_(_) (_) |_(_) ___  ___
# | | | | __| | | | __| |/ _ \/ __|
# | |_| | |_| | | | |_| |  __/\__ \
#  \__,_|\__|_|_|_|\__|_|\___||___/

#  ____             _       _    _
# / ___| _ __  _ __(_)_ __ | | _| | ___ _ __ ___
# \___ \| '_ \| '__| | '_ \| |/ / |/ _ \ '__/ __|
#  ___) | |_) | |  | | | | |   <| |  __/ |  \__ \
# |____/| .__/|_|  |_|_| |_|_|\_\_|\___|_|  |___/
#       |_|

- alias: "Utilities: sprinklers update start"
  mode: single
  trigger:
    - platform: device
      type: turned_on
      device_id: f2a4a3a5edd8f8d1bf905bec17fc72cd
      entity_id: switch.main_schedule
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.sprinklers_on"
        timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: sprinklers update done"
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: f2a4a3a5edd8f8d1bf905bec17fc72cd
      entity_id: switch.main_schedule
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.sprinklers_off"
        timestamp: "{{ now().timestamp() }}"

#      _ _     _                      _
#   __| (_)___| |____      ____ _ ___| |__   ___ _ __
#  / _` | / __| '_ \ \ /\ / / _` / __| '_ \ / _ \ '__|
# | (_| | \__ \ | | \ V  V / (_| \__ \ | | |  __/ |
#  \__,_|_|___/_| |_|\_/\_/ \__,_|___/_| |_|\___|_|
#

- alias: "Utilities: dishwasher update start"
  mode: single
  trigger:
    - platform: device
      type: turned_on
      device_id: 4600d3f0392dd39f2f1029862db62605
      entity_id: switch.dishwasher
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.dishwasher_on"
        timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: dishwasher update done"
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: 4600d3f0392dd39f2f1029862db62605
      entity_id: switch.dishwasher
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.dishwasher_off"
        timestamp: "{{ now().timestamp() }}"

#                   _
#__      ____ _ ___| |__   ___ _ __
#\ \ /\ / / _` / __| '_ \ / _ \ '__|
# \ V  V / (_| \__ \ | | |  __/ |
#  \_/\_/ \__,_|___/_| |_|\___|_|
#
- alias: "Utilities: washer update start"
  mode: single
  trigger:
    - platform: device
      type: turned_on
      device_id: 8d6e03b47a9406ee35459588a713ce9f
      entity_id: switch.washer_power_off
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.washing_machine_on"
        timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: washer update done"
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: 8d6e03b47a9406ee35459588a713ce9f
      entity_id: switch.washer_power_off
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.washing_machine_off"
        timestamp: "{{ now().timestamp() }}"
#  ____
# |  _ \ _ __ _   _  ___ _ __
# | | | | '__| | | |/ _ \ '__|
# | |_| | |  | |_| |  __/ |
# |____/|_|   \__, |\___|_|
#             |___/
- alias: "Utilities: dyer update start"
  mode: single
  trigger:
    - platform: device
      type: turned_on
      device_id: 523f0fb01b184dea0bad7ecfb9b6552a
      entity_id: switch.dryer_power_off
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.dryer_machine_on"
        timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: dryer update done"
  mode: single
  trigger:
    - platform: device
      type: turned_off
      device_id: 523f0fb01b184dea0bad7ecfb9b6552a
      entity_id: switch.dryer_power_off
      domain: switch
  condition: []
  action:
    - service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.dryer_machine_off"
        timestamp: "{{ now().timestamp() }}"

#      _                                      _
#  ___| | ___  ___ _ __    _ __ ___  ___  ___| |_
# / __| |/ _ \/ _ \ '_ \  | '__/ _ \/ __|/ _ \ __|
# \__ \ |  __/  __/ |_) | | | |  __/\__ \  __/ |_
# |___/_|\___|\___| .__/  |_|  \___||___/\___|\__|
#                 |_|

- alias: "Utilities: Reset sleep status"
  mode: single
  trigger:
    platform: time
    at: "10:00:00"
  condition: []
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sleeping
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.guest_sleeping
