---
#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#

- platform: template
  sensors:
    someone_showering:
      friendly_name: Someone is showering
      value_template: >
        {% set humidity = states("sensor.lumi_lumi_weather_humidity") | float(0) %}
        {% set treshold = 1.05 * state_attr("sensor.humidity_bathroom_stats", "median") | float(0) %}
        {% set derivative = states("sensor.humidity_bathroom_derivative") | float(0) %}
        {{ humidity > treshold and derivative > 0.25 }}

    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_guest_bedroom", "on")
            or is_state("binary_sensor.activity_in_hall", "on")
            or is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_living_room", "on")
            or is_state("binary_sensor.activity_in_loft", "on")
            or is_state("binary_sensor.activity_in_master_bedroom", "on") }}

    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on")
            or is_state("group.persons", "home") }}

    activity_in_living_room:
      friendly_name: Activity in the living room
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_2", "on")
            or is_state("media_player.living_room", "on")
        }}
      delay_off: "00:20:00"

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_motion_ac02_iaszone_2", "on") }}
      delay_off: "00:01:00"

    activity_in_hall:
      friendly_name: Activity in the hall
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_motion_ac02_iaszone_3", "on") }}
      delay_off: "00:01:00"

    activity_in_master_bedroom:
      friendly_name: Activity in the master bedroom
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_4", "on") }}
      delay_off: "00:01:00"

    activity_in_guest_bedroom:
      friendly_name: Activity in the guest bedroom
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_motion_ac02_iaszone", "on") }}
      delay_off: "00:01:00"

    activity_in_loft:
      friendly_name: Activity in the Loft
      value_template: >
        {{ is_state("binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_3", "on")
            or is_state("media_player.loft", "on")
        }}
      delay_off: "00:20:00"

    dishwasher:
      friendly_name: Dishwasher
      value_template: >
        {{ is_state("sensor.dishwasher_dishwasher_machine_state", "run") }}
      delay_off: "00:03:00"
      icon_template: >
        {% if is_state("binary_sensor.dishwasher", "on") %}
          mdi:dishwasher
        {% else %}
          mdi:dishwasher-off
        {% endif %}

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set automatic_lights_on = is_state("light.automatic_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.living_room_lights", "on") %}
        {{ automatic_lights_on or bedroom_lights_on or living_room_lights_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.tv", "on") %}
        {% set kef_on = is_state("media_player.kef_ls50", "on") %}
        {% set kef_lsx_on = is_state("media_player.kef_lsx", "on") %}
        {{ light_on or tv_on or kef_on or kef_lsx_on }}

    vacuum_day:
      friendly_name: Vacuum day today
      value_template: >
        {{ as_timestamp(now()) | timestamp_custom("%a") in ("Mon", "Wed", "Fri") }}

    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.tony_pacheco", "home")
            and not is_state("person.lloyd_chan", "home") }}

- platform: workday
  country: US

- platform: trend
  sensors:
    humidity_bathroom_trend:
      entity_id: sensor.lumi_lumi_weather_humidity
      sample_duration: 300
      max_samples: 3
