---
#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#

#  _____                    _       _
# |_   _|__ _ __ ___  _ __ | | __ _| |_ ___    ___  ___ _ __  ___  ___  _ __ ___
#   | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \  / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
#   | |  __/ | | | | | |_) | | (_| | ||  __/  \__ \  __/ | | \__ \ (_) | |  \__ \
#   |_|\___|_| |_| |_| .__/|_|\__,_|\__\___|  |___/\___|_| |_|___/\___/|_|  |___/
#                    |_|

- platform: template
  sensors:
    fridge_watts:
      value_template: >
        {{ states("sensor.refrigerator_power") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Fridge usage

    dishwasher_watts:
      value_template: >
        {{ states("sensor.dishwasher_power") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Dishwasher usage

    washer_watts:
      value_template: >
        {{ states("sensor.dishwasher_power") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Dishwasher usage

    # washer and dryer does not have power output
    # dryer_watts:
    #   value_template: >
    #     {{ states("sensor.dishwasher_power") | float("Unavailable") }}
    #   unit_of_measurement: Watt
    #   friendly_name: Dishwasher usage

    count_automations:
      icon_template: mdi:autorenew
      value_template: "{{ states.automation | count }}"

    count_scripts:
      icon_template: mdi:script-text-outline
      value_template: "{{ states.script| count }}"

    count_device_trackers:
      icon_template: mdi:map-marker
      value_template: "{{ states.device_tracker | count }}"

    count_binary_sensors:
      icon_template: mdi:unfold-more-horizontal
      value_template: "{{ states.binary_sensor| count }}"

    count_sensors:
      icon_template: mdi:resistor
      value_template: "{{ states.sensor | count }}"

    count_switches:
      icon_template: mdi:light-switch
      value_template: "{{ states.switch | count }}"

    count_zones:
      icon_template: mdi:map-marker-radius
      value_template: "{{ states.zone | count }}"

    count_input_booleans:
      icon_template: mdi:toggle-switch
      value_template: "{{ states.input_boolean | count }}"

    count_input_numbers:
      icon_template: mdi:numeric
      value_template: "{{ states.input_number | count }}"

    count_input_texts:
      icon_template: mdi:alphabetical
      value_template: "{{ states.input_text | count }}"

    count_input_selects:
      icon_template: mdi:view-list
      value_template: "{{ states.input_select | count }}"

    count_input_datetimes:
      icon_template: mdi:calendar-clock
      value_template: "{{ states.input_datetime | count }}"

    timestamp_start_of_today:
      value_template: >
        {{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) }}
      unit_of_measurement: "s"

    n_days_last_month:
      value_template: >
        {% set start_of_month = now().replace(day=1) %}
        {% set start_of_last_month = start_of_month.replace(month=now().month-1) %}
        {{ ((start_of_month - start_of_last_month).total_seconds() / 86400) | round }}

    nearest_iphone_notify:
      friendly_name: Nearest iPhone's notify service
      value_template: >
        {% if is_state("person.tony_pacheco", "home") and is_state("person.lloyd_chan", "home") %}
          notify.all_iphones
        {% elif is_state_attr("proximity.home", "nearest", "antonios_iphone_2") %}
          notify.antonios_iphone_2
        {% else %}
          notify.lloyds_iphone
        {% endif %}

    half_hour_before_alarm:
      friendly_name: Half an hour before alarm
      value_template: >
        {% set t_alarm = state_attr("input_datetime.alarm_clock", "timestamp") | int %}
        {% set t_start = states("sensor.timestamp_start_of_today") | int %}
        {% set half_hour_before_alarm = t_alarm + t_start - 60 * 30 %}
        {{ half_hour_before_alarm | timestamp_custom("%H:%M", True) }}

    ten_minutes_before_alarm:
      friendly_name: Ten minutes before alarm
      value_template: >
        {% set t_alarm = state_attr("input_datetime.alarm_clock", "timestamp") | int %}
        {% set t_start = states("sensor.timestamp_start_of_today") | int %}
        {% set before_alarm = t_alarm + t_start - 60 * 10 %}
        {{ before_alarm | timestamp_custom("%H:%M", True) }}

    hours_outside_per_day_lloyd:
      friendly_name: Hours outside per day (Lloyd)
      value_template: >
        {% set value = state_attr("sensor.quarantine_meter_lloyd", "value") %}
        {% if value != None %}

        {% set nargs = 1 + (value | length) - (value.replace(' ', '') | length) %}
        {% if nargs < 2 %}{% set value = "0h " ~ value %}{% endif %}
        {% if nargs < 3 %}{% set value = "0d " ~ value %}{% endif %}

        {% set d, h, m = value.split() %}
        {% set d, h, m = d[:-1] | int, h[:-1] | int, m[:-1] | int %}
        {% set hours_outside = ((14 - d) * 86400 - h * 3600 - m * 60) / 3600 %}
        {{ (hours_outside / 14) | round(1) }}
        {% endif %}

    hours_outside_per_day_tony:
      friendly_name: Hours outside per day (Tony)
      value_template: >
        {% set value = state_attr("sensor.quarantine_meter_tony", "value") %}
        {% if value != None %}

        {% set nargs = 1 + (value | length) - (value.replace(' ', '') | length) %}
        {% if nargs < 2 %}{% set value = "0h " ~ value %}{% endif %}
        {% if nargs < 3 %}{% set value = "0d " ~ value %}{% endif %}

        {% set d, h, m = value.split() %}
        {% set d, h, m = d[:-1] | int, h[:-1] | int, m[:-1] | int %}
        {% set hours_outside = ((14 - d) * 86400 - h * 3600 - m * 60) / 3600 %}
        {{ (hours_outside / 14) | round(1) }}
        {% endif %}

    lights_on_total_hours:
      unit_of_measurement: h
      value_template: >
        {{ states('sensor.hours_bedroom_lights_have_been_on_last_7_days')|float * 1
            + states('sensor.hours_bedroom_night_light_have_been_on_last_7_days')|float * 1
            + states('sensor.hours_entrance_lights_have_been_on_last_7_days')|float * 1
            + states('sensor.hours_kitchen_lights_have_been_on_last_7_days')|float * 4
            + states('sensor.hours_living_room_lights_have_been_on_last_7_days')|float * 5
            + states('sensor.hours_loft_lights_have_been_on_last_7_days')|float * 5
            + states('sensor.hours_porche_lights_have_been_on_last_7_days')|float * 2
            + states('sensor.hours_stair_lights_have_been_on_last_7_days')|float * 2 }}

    lights_on_total_kwh:
      unit_of_measurement: h
      value_template: >
        {{ states('sensor.lights_on_total_hours')|float * 5.4 / 1000 }}

    living_room_tv_volume:
      value_template: >
        {{ state_attr("media_player.living_room", "volume_level") }}
      unit_of_measurement: "%"

    loft_tv_volume:
      value_template: >
        {{ state_attr("media_player.loft", "volume_level") }}
      unit_of_measurement: "%"

#   ___  _   _
#  / _ \| |_| |__   ___ _ __ ___
# | | | | __| '_ \ / _ \ '__/ __|
# | |_| | |_| | | |  __/ |  \__ \
#  \___/ \__|_| |_|\___|_|  |___/
#

- platform: statistics
  name: Humidity bathroom stats
  entity_id: sensor.lumi_lumi_weather_humidity
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age: "24:00:00"
  state_characteristic: mean

- platform: derivative
  source: sensor.lumi_lumi_weather_humidity
  name: Humidity bathroom derivative
  unit_time: min
  time_window: "00:10:00"

# XXX: not used
- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.nest_temperature #2nd floor
    - sensor.thermostat_1_nativezone_temperature #first floor
    - sensor.lumi_lumi_weather_temperature #bathroom

- platform: time_date
  display_options:
    - date
    - time

# Set up on Proxmox https://community.home-assistant.io/t/intel-nuc-proxmox-cpu-temperature-monitor-with-python-mqtt/194236/8
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_temperature
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: last_boot

- platform: uptime

- platform: command_line
  command: !secret portfolio_value
  name: portfolio_value
  unit_of_measurement: "$"
  scan_interval: 20

#  _____ _                  _                  _
# |_   _(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __ ___
#   | | | | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__/ __|
#   | | | | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |  \__ \
#   |_| |_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|  |___/
#

- platform: history_stats
  name: Hours Living room TV has been on last 7 days
  entity_id: media_player.living_room
  state:
    - "playing"
    - "idle"
    - "paused"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times Living room TV has been on last 7 days
  entity_id: media_player.living_room
  state: "standby"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours Loft TV has been on last 7 days
  entity_id: media_player.loft
  state:
    - "playing"
    - "idle"
    - "paused"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times Loft TV has been on last 7 days
  entity_id: media_player.loft
  state: "standby"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours fridge has been open last 7 days
  entity_id: binary_sensor.refrigerator_contact
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times fridge has been open last 7 days
  entity_id: binary_sensor.refrigerator_contact
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dishwasher has been on last 7 days
  entity_id: sensor.dishwasher_dishwasher_machine_state
  state: "run"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times dishwasher has been on last 7 days
  entity_id: sensor.dishwasher_dishwasher_machine_state
  state: "run"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: sensor.washer
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times washing machine has been on last 7 days
  entity_id: sensor.washer
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dryer machine has been on last 7 days
  entity_id: sensor.dryer
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times dyer machine has been on last 7 days
  entity_id: sensor.dryer
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Tony
  entity_id: person.tony_pacheco
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Lloyd
  entity_id: person.lloyd_chan
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Tony times left
  entity_id: person.tony_pacheco
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine meter Lloyd times left
  entity_id: person.lloyd_chan
  state: "home"
  type: count
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bedroom lights have been on last 7 days
  entity_id: light.bedroom_fan_light
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours Loft lights have been on last 7 days
  entity_id: light.loft_ceiling_fan_light
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours stair lights have been on last 7 days
  entity_id: light.stairs_main_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours porche lights have been on last 7 days
  entity_id: light.front_porch_overhead_light
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours living room lights have been on last 7 days
  entity_id: light.living_room_ceiling_fan_light
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours kitchen lights have been on last 7 days
  entity_id: light.kitchen_main_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours entrance lights have been on last 7 days
  entity_id: light.entry_way_lamp_on_off
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bedroom night light have been on last 7 days
  entity_id: light.bedroom_night_light
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"
#     _    _                          _ _ _
#    / \  (_)_ __    __ _ _   _  __ _| (_) |_ _   _
#   / _ \ | | '__|  / _` | | | |/ _` | | | __| | | |
#  / ___ \| | |    | (_| | |_| | (_| | | | |_| |_| |
# /_/   \_\_|_|     \__, |\__,_|\__,_|_|_|\__|\__, |
#                      |_|                    |___/

- platform: waqi
  token: !secret aqcin_token
  locations:
    - Santa Clarita-Placerita, Los Angeles
