#-
#               _ _       _
#  _____      _(_) |_ ___| |__   ___  ___
# / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# \__ \\ V  V /| | || (__| | | |  __/\__ \
# |___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#
#
- platform: template
  switches:
    first_floor_vacuum_mode:
      value_template: >
        {{ is_state("vacuum.roomba", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.roomba
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.roomba

- platform: template
  switches:
    first_floor_mop_mode:
      value_template: >
        {{ is_state("vacuum.braava_jet", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.braava_jet
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.braava_jet
